name: Reusable workflow user

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

  docker:
    uses: Nmnaren/skills-test-with-actions/.github/workflows/reusable.yaml@main
    with:
      image_name: my-awesome-app
      tag: ${{ github.run_number }}
    secrets:
      username: ${{ secrets.dockerusername }}
      password: ${{ secrets.dockerpassword }}
